import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage<{ data: any }> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nasa image thumbs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Thumnnails:</h1>

      <br />

      <div className={styles.imageWrapper}>
        {data.map(
          (
            item: { href: string; rel: string; render: 'string' },
            index: number
          ) => (
            <div key={index}>
              {/* eslint-disable-next-line */}
              <img src={item.href} alt="Thumbnail" className={styles.image} />
            </div>
          )
        )}
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const response = await fetch('http://localhost:3000/api/thumbs/');
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}

export default Home;
